DoubleQuotedStringLiteralQ = "%" "Q"? ((Delimiter ("NOT Delimiter OR '\'" | CharacterEscape)* Delimiter) | "(" ("NOT '(' OR ')'" | CharacterEscape )* ")" | "[" ("NOT '[' OR ']'" | CharacterEscape )*"]" | "{" ("NOT '{' OR '}'" | CharacterEscape)* "}" | "<" ("NOT '<' OR '>'" | CharacterEscape)* ">")
