HereDocument = "<<" (
  (
   (Identifier | StringLiteral) Expression? "\\n" Character* "\\n" (Identifier | StringLiteral)
  ) 
  | 
  (
    "-" (Identifier | StringLiteral) Expression? "\\n" Character* "\\n" " "* (Identifier | StringLiteral)
  )
)
